# Generated by Django 4.2.4 on 2023-08-19 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0006_order_delivered_alter_order_delivery_crew_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_assigned_to',
        ),
    ]
